#This file builds the Docker images for a React/NodeJS application and runs it as microservices on Docker containers

#To ensure successful execution, clone this entire repository and execute this file while in the root folder of the cloned repository

#It's also a requirement to have Docker and the docker-compose plugin installed in your environment

#To launch this app without having to clone the entire repository,use the docker-compose.yaml file to run the app

#version: "3.9"

services:
  mongo:
    image: mongo:5.0
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - yolonet

  backend:
    build:
      context: ./backend  
      dockerfile: Dockerfile
    image: yolo-backend:1.0.0
    container_name: yolo-backend
    restart: always
    #env_file:
     # - ./server/.env
    environment:
      - MONGO_URI=mongodb://mongo-db:27017/yolo
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    networks:
      - yolonet

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: yolo-frontend:1.0.0
    container_name: yolo-client
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - yolonet

volumes:
  mongo_data:

networks:
  yolonet:
    driver: bridge
